### ISSUE TITLE
Discord embed black color only problem 

### ISSUE THREAD

**Issue by Amylaberi** [abramkremer/embed-generator#2]
I am not sure I understand your hexadecimal format, because I search up for the format and plug them in, but all it returns to me in black. Do you have any ideas that can help me? Please answer as soon as possible!

**Comment by abramkremer** [comment]
Hello, the format for picking a color looks like {FF0000 for red, {00FF00 for green. That sort of thing. I assume the confusion is because you probably expected to input #FF0000 or maybe {#FF0000. Let me know if this helps/works.

**Comment by Amylaberi** [comment]
> Hello, the format for picking a color looks like {FF0000 for red, {00FF00 for green. That sort of thing. I assume the confusion is because you probably expected to input #FF0000 or maybe {#FF0000. Let me know if this helps/works.

Maybe my generator is broken? It still not working for me. It returns back black again. Would you like me to share a google doc of it, maybe that can help?

**Comment by abramkremer** [comment]
If you would like to add me to the server for a moment we can take a look. As you mentioned it's also possible that the generator is no longer working due to updates to the Discord.js module.

**Comment by Amylaberi** [comment]
Sure!

**Comment by abramkremer** [comment]
My username is InStock#9416

**Comment by Amylaberi** [comment]
https://discord.gg/PzK276jT
