### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by NaCl10** [abramkremer/embed-generator#3]
Hey! I'm looking into potentially using or adapting parts of this code in a project of mine (with credit given of course), but I'm not sure if that's permitted when there's no license.

If you're unsure of what license to use or just want more information about what they are, what they do, and why you need them, check out [choosealicense.com](https://choosealicense.com). It's a site created by GitHub themselves for the exact purpose of informing people of what licenses are, what they do, and why the're needed.

**Comment by abramkremer** [comment]
Thanks for letting me know, I've added a license.
